export const TIMTIM_ALREADY_SELECTED_CITY_COOKIE = 'TIMTIM_ALREADY_SELECTED_CITY_COOKIE';

export const TIMTIM_ALREADY_SELECTED_LANGUAGE_COOKIE = 'TIMTIM_ALREADY_SELECTED_LANGUAGE_COOKIE';

export const FavouriteTypes = {
  rentAndSale: 'RENT_AND_SALE',
  complexes: 'COMPLEXES',
  layouts: 'LAYOUTS',
};
